export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const GET_CONFIG_REQUEST = 'GET_CONFIG_REQUEST';
export const GET_CATEGORY_NEWS_REQUEST = 'GET_CATEGORY_NEWS_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const UNSAVE_NEWS_RESPONSE = 'UNSAVE_NEWS_RESPONSE';
export const MANUAL_ENABLE_NIGHT_MODE = 'MANUAL_ENABLE_NIGHT_MODE';

export const LOGIN_ADMIN_REQUEST = 'LOGIN_ADMIN_REQUEST';
export const LOGIN_ADMIN_RESPONSE = 'LOGIN_ADMIN_REQUEST';
